on: [push]
name: Cypress Demo Project CI

jobs:
  test:
    runs-on: ubuntu-18.04
    name: check tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: testomatio/check-tests@stable
      with:
        framework: cypress
        tests: "./cypress/integration/**/**.spec.js"
        has-tests-label: true