name: run Cypress Demo Tests
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  RECORD_KEY: ${{secrets.RECORD_KEY}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          browser: firefox
          record: true

  